#!/bin/sh
#
# OpenBMC serial console service
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/obmc-console-server
DAEMON_OPTS=ttyS0
NAME=obmc-console-server

test -x "${DAEMON}" || exit 0

case "$1" in
  start)
 	echo "Starting OpenBMC console server..."
	start-stop-daemon --start --background --quiet --make-pidfile --pidfile=/run/${NAME}.pid --exec ${DAEMON} -- ${DAEMON_OPTS}
	exit $?
	;;
  stop)
	echo "Stopping OpenBMC console server..."
	start-stop-daemon --stop --quiet --pidfile=/run/${NAME}.pid --exec ${DAEMON}
	RETVAL=$?
	rm -rf /run/${NAME}.pid
	exit $?
	;;
  restart|reload)
	"$0" stop
	"$0" start
	exit $?
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 3
esac

exit 0

